# Generated by Django 5.0.2 on 2024-04-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travel', '0002_remove_booking_address_remove_booking_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='status',
            new_name='Verification',
        ),
    ]
