# Generated by Django 5.0.2 on 2024-04-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travel', '0003_rename_status_booking_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
