# Generated by Django 5.0.2 on 2024-04-17 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travel', '0004_booking_phone_booking_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='quantity',
            new_name='no_of_people',
        ),
    ]
