# Generated by Django 5.0.2 on 2024-04-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travel', '0005_rename_quantity_booking_no_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1200, null=True),
        ),
    ]
